spring:
  application:
    name: order-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ORDERS
    password: ORDERS
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.OracleDialect

server:
  port: 8002

coupon:
  service:
    url: http://coupon-service/validate?{{COUPON_CODE}} # GET

bank:
  service:
    url: http://bank-service/payments # POST

store:
  service:
    url: https://0fce001b-0649-4991-b90d-0bcac73b7883.mock.pstmn.io

# RabbitMQ configuration
rabbitmq:
  exchange:
    notification: notification-exchange
  routingkey:
      notification: order-notification
  host: localhost
  port: 5672
  username: guest
  password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
